apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticview.fullname" . }}-elasticview
  labels:
    app: elasticview
  {{- include "elasticview.labels" . | nindent 4 }}
spec:
  type: {{ .Values.elasticview.type }}
  selector:
    app: elasticview
  {{- include "elasticview.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.elasticview.ports | toYaml | nindent 2 }}